# Generated by Django 4.0.3 on 2022-03-11 09:58

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseaccount',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='baseaccount',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='email',
            field=models.EmailField(help_text='This will be used as username for login', max_length=350, unique=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can edit everything into this admin site.', verbose_name='admin status'),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
