# Generated by Django 4.0.3 on 2022-03-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseaccount_options_alter_baseaccount_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseaccount',
            managers=[
            ],
        ),
    ]
