# Generated by Django 4.0.3 on 2022-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseaccount_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseaccount',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user can edit everything into this admin site.', verbose_name='admin status'),
        ),
    ]
