# Generated by Django 4.0.3 on 2022-03-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_baseaccount_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseaccount',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
