# Generated by Django 4.0.3 on 2022-03-11 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_baseaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='contact_no',
            field=models.CharField(blank=True, db_index=True, help_text='\n            👌🏻E.g - 9881284481\n            ❌ +91 9812300122\n            ❌ 09812300122\n        ', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone no should contain 10 digits')], verbose_name='Phone No(without country code or 0)'),
        ),
    ]
