# Generated by Django 4.0.3 on 2022-03-12 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testprofile.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_baseaccount_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=350, verbose_name='Department Name')),
                ('domain', models.CharField(help_text='e.g., Domain : Computer Science', max_length=300, verbose_name='Domain Name')),
                ('degree', models.CharField(blank=True, choices=[("Bachelor's Degree", 'BACHELORS'), ("Master's Degree", 'MASTERS'), ('PhD', 'PHD'), ('Diploma', 'DIPLOMA')], default=testprofile.constants.Degree['BACHELORS'], max_length=100, verbose_name='Degree Level')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university_roll', models.PositiveSmallIntegerField(db_index=True, help_text='Your University Roll No - (e.g. - 13071020030)', unique=True, verbose_name='University Roll')),
                ('current_sem', models.CharField(choices=[('1-st', 'FIRST'), ('2-nd', 'SECOND'), ('3-rd', 'THIRD'), ('4-th', 'FORTH'), ('5-th', 'FIFTH'), ('6-th', 'SIXTH'), ('7-th', 'SEVENTH'), ('8-th', 'EIGHTH'), ('9-th', 'NINTH'), ('10-th', 'TENTH')], db_index=True, default=testprofile.constants.Semester['FIRST'], help_text='Select Your On Going Sem🔢', max_length=10, verbose_name='Choose Sem [1-10]-th')),
                ('depertment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='testprofile.department')),
            ],
        ),
    ]
