# Generated by Django 4.0.3 on 2022-03-12 15:59

from django.db import migrations, models
import testprofile.constants


class Migration(migrations.Migration):

    dependencies = [
        ('testprofile', '0002_alter_department_degree_alter_student_current_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='degree',
            field=models.PositiveSmallIntegerField(blank=True, choices=[("Bachelor's Degree", 'BACHELORS'), ("Master's Degree", 'MASTERS'), ('PhD', 'PHD'), ('Diploma', 'DIPLOMA')], default=testprofile.constants.Degree['BACHELORS'], verbose_name='Degree Level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.PositiveSmallIntegerField(choices=[('1-st', 'FIRST'), ('2-nd', 'SECOND'), ('3-rd', 'THIRD'), ('4-th', 'FORTH'), ('5-th', 'FIFTH'), ('6-th', 'SIXTH'), ('7-th', 'SEVENTH'), ('8-th', 'EIGHTH'), ('9-th', 'NINTH'), ('10-th', 'TENTH')], db_index=True, default=testprofile.constants.Semester['FIRST'], help_text='Select Your On Going Sem🔢', verbose_name='Choose Sem [1-10]-th'),
        ),
    ]
