# Generated by Django 4.0.3 on 2022-03-12 16:07

from django.db import migrations, models
import testprofile.constants


class Migration(migrations.Migration):

    dependencies = [
        ('testprofile', '0003_alter_department_degree_alter_student_current_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='degree',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD'), ('DIPLOMA', 'Diploma')], default=testprofile.constants.Degree['BACHELORS'], verbose_name='Degree Level'),
        ),
    ]
