# Generated by Django 4.0.3 on 2022-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprofile', '0005_alter_department_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='degree',
            field=models.CharField(blank=True, choices=[('BS', "Bachelor's Degree"), ('MS', "Master's Degree"), ('PHD', 'PhD'), ('DPL', 'Diploma')], default='BS', max_length=5, verbose_name='Degree Level'),
        ),
    ]
