# Generated by Django 4.0.3 on 2022-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprofile', '0007_alter_student_current_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_roll',
            field=models.PositiveBigIntegerField(db_index=True, help_text='Your University Roll No - (e.g. - 13071020030)', unique=True, verbose_name='University Roll'),
        ),
    ]
